name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run Tests
      run: ./gradlew test
      
    - name: Build Docker image
      run: docker build -t skuullking/devsecops:latest .
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: github.ref == 'refs/heads/main'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: docker push skuullking/devsecops:latest
      
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Configure kubectl
      run: |
        # This step would set up your kubeconfig file
        # For example, using secrets or cloud-specific actions
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl rollout restart deployment car-rental-app
